name: Crystal CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: shards install
    - name: Run tests
      env:
        NEXPLOIT_TOKEN: ${{ secrets.NEXPLOIT_TOKEN }}
        NEXPLOIT_REPEATER: ${{ secrets.NEXPLOIT_REPEATER }}
      run: crystal spec
