name: Crystal CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: shards install
    - name: Install npm and Repeater
      run: |
        apt update
        apt-get install nodejs-dev node-gyp libssl1.0-dev
        apt-get install nodejs npm
        npm install -g @neuralegion/nexploit-cli --unsafe-perm=true
    - name: Run tests
      env:
        NEXPLOIT_TOKEN: ${{ secrets.NEXPLOIT_TOKEN }}
        NEXPLOIT_REPEATER: ${{ secrets.NEXPLOIT_REPEATER }}
      run: crystal spec
